Added logic to trim away leading/trailing whitespaces in user-clipboard auto-inputted urls
gpodder/gpodder pull request #1276
Opened 2022-04-16 06:18 UTC by Lexora

# Added logic to trim away leading/trailing whitespaces in user-clipboard auto-inputted urls  
### Type: feat 

Tested against current gpodder-installed executable for correct/desired 
behaviour. simplified receive_clipboard_text method of class
gPodderAddPodcast in addpodcast.py -- 

Resolves: #520

2022-04-16 09:45 UTC, tpikonen requested changes

2022-04-16 09:45 UTC, tpikonen commented on src/gpodder/util.py
> +    logger.warning(f'{error_message}', stack_info=True)
The separate var for `error_message` is not needed, just use a string constant argument in the call and break lines if they are longer than 79 chars.

The minimum Python version for gPodder is 3.5, where f-strings are not supported. Please use other formatting methods.

Also, I'm not sure if `stack_info` is really needed here.

2022-04-16 09:45 UTC, tpikonen commented on src/gpodder/util.py
> +        logger.warning(f'{error_message}', stack_info=True)
Same here.

2022-04-16 09:45 UTC, tpikonen commented on src/gpodder/util.py
> +        url = f'http://{url}'
Not really needed and uses an f-string.

2022-04-16 09:46 UTC, tpikonen commented
Thanks for the patch, see my review for comments.

2022-04-17 04:11 UTC, Lexora commented
Thanks for the tips @tpikonen - added commit to update & address requested changes :)

2022-04-17 05:11 UTC, merged

2022-04-17 05:12 UTC, auouymous commented
Thank you for the patch.