Add winget releaser github action
gpodder/gpodder pull request #1380
Opened 2022-08-28 16:47 UTC by aman207

Discussion in #1378 

You will need to create a github personal access token and add it to the secrets within the repository. More info here (https://bittu.eu.org/docs/wr-intro) & here (https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow)

2022-09-01 15:49 UTC, vedantmgoyal2009 requested changes

2022-09-01 15:49 UTC, vedantmgoyal2009 commented on .github/workflows/winget-releaser.yml
> +          token: ${{ secrets.WINGET_TOKEN }}
```suggestion
          installers-regex: 'installer\.exe$' # only the installer.exe file
          token: ${{ secrets.WINGET_TOKEN }}
```

2022-09-09 10:15 UTC, vedantmgoyal2009 commented
cc @auouymous

2022-09-12 21:13 UTC, elelay commented
Call me paranoid but I'm not confident entrusting a private token to a 3rd party app.

public_repo | Limits access to  public repositories. That includes read/write access to code, commit  statuses, repository projects, collaborators, and deployment statuses  for public repositories and organizations. Also required for starring  public repositories.
-- | --

2022-09-13 01:03 UTC, auouymous commented
I haven't had time to look at this yet, but if it really does need write access then I'd say no. We already run github_release.py with a public_repo token that could easily be modified to push a winget release without exposing the repo to any third parties.

2022-09-13 10:39 UTC, vedantmgoyal2009 commented
The personal access token is used to create a pull request on https://github.com/microsoft/winget-pkgs to update the manifests and not for any other purposes.

2022-09-14 17:46 UTC, elelay commented
Yes it is intended to be used to open a PR, but it is consumed by an unspecified version (`@latest`) of the app, which then calls an [unspecified version of a powershell](https://github.com/vedantmgoyal2009/winget-releaser/blob/main/index.js#L65).

2022-09-24 17:22 UTC, elelay requested changes
Due to security concerns with giving a personal token I'm against this addition.

2022-09-24 17:25 UTC, elelay commented
> > Yes it is intended to be used to open a PR, but it is consumed by an unspecified version (`@latest`) of the app, which then calls an [unspecified version of a powershell](https://github.com/vedantmgoyal2009/winget-releaser/blob/main/index.js?rgh-link-date=2022-09-14T17%3A46%3A08Z#L65).
> 
> It is the PowerShell script for updating manifests using data from previous manifests. The source of the file can be found in the root of the action's repository (https://github.com/vedantmgoyal2009/winget-releaser/blob/main/YamlCreate.ps1).
> 
> The `latest` in the URL is to use the script from `latest` tag, since the `main` branch has untested changes, which may break the action.

To be clear, based on a cursory glance I didn't find anything wrong with your app (I'm not able to judge the powershell dependencies). My issue is with future changes. I was going to request thay you reference a precise application version and a precise tag in your app instead of `latest` but a malicious actor could just as well force-push new tags to your repository. Immutable github apps would be necessary to reassure me.

2022-09-24 18:45 UTC, aman207 commented
The release is actually called latest as you can see here: https://github.com/vedantmgoyal2009/winget-releaser/releases/tag/latest

According to the github documentation, anything after @ is referencing a tag or branch on the target action (https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management). So it seems like its not actually referencing the latest version of the code but rather a tag named 'latest'

2022-09-24 18:55 UTC, aman207 commented
Regarding the concerns with a personal access token, could we create another github account with no ties to this project? There just needs to be _an_ account that sends a pull request to winget-pkgs

2022-09-24 21:57 UTC, elelay commented
> We could also reference the SHA of a specific commit (https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-a-commits-sha-for-release-management). Then its impossible for an attacker to takeover the tag or branch and publish malicious code.

This might be a good idea. And reference that in https://github.com/vedantmgoyal2009/winget-releaser/blob/latest/index.js#L72 because the app currently downloads anything with the tag latest. But now you get to commit twice and re-push your "latest" tag at any change in the powershell, not the most convenient...

2022-09-24 23:59 UTC, aman207 commented
Can't speak to the edit of index.js, that'll have to be something @vedantmgoyal2009 speaks to. I added a commit with the most recent SHA on the 'latest' tag.

2022-09-25 02:55 UTC, vedantmgoyal2009 commented
> This might be a good idea. And reference that in [https://github.com/vedantmgoyal2009/winget-releaser/blob/latest/index.js#L72](https://github.com/vedantmgoyal2009/winget-releaser/blob/latest/index.js?rgh-link-date=2022-09-24T21%3A57%3A49Z#L72) because the app currently downloads anything with the tag latest

That can be solved via `${{ github.action_ref }}`

Reference: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

2022-09-25 05:12 UTC, vedantmgoyal2009 commented on .github/workflows/winget-releaser.yml
> +      - uses: vedantmgoyal2009/winget-releaser@0727cc2cdf0f3ecafd492608d2aff67b13adff55
```suggestion
      - uses: vedantmgoyal2009/winget-releaser@1492f6
```

2022-09-25 05:23 UTC, vedantmgoyal2009 commented on .github/workflows/winget-releaser.yml
> +      - uses: vedantmgoyal2009/winget-releaser@0727cc2cdf0f3ecafd492608d2aff67b13adff55
https://github.com/vedantmgoyal2009/winget-releaser/blob/1492f6c8620789a03865436b2eb95c6a944f8405/index.js#L68

cc @elelay

2022-09-28 13:11 UTC, vedantmgoyal2009 commented
https://github.com/vedantmgoyal2009/winget-releaser/blob/1492f6c8620789a03865436b2eb95c6a944f8405/index.js#L68

cc @elelay @aman207

2024-09-10 15:34 UTC, closed without merging