Updated French translation
gpodder/gpodder pull request #1421
Opened 2022-10-11 16:01 UTC by rene-coty

I updated the fr.po file

2022-10-11 19:37 UTC, elelay commented on po/fr.po
> +msgstr "Retirer les épisodes supprimés de gPodder du périphérique"
Retirer du périphérique les épisodes supprimés dans gPodder

2022-10-11 19:42 UTC, elelay requested changes
Thank you for the translation.
Looks good to me except one sentence that I would rephrase (see comment).

Also I'm not sure why you removed the space following colon, which I would consider necessary in French. Please explain :-)

2022-10-11 22:08 UTC, rene-coty commented
> Thank you for the translation. Looks good to me except one sentence that I would rephrase (see comment).

Okay I'll change it :+1:

2022-10-11 22:09 UTC, rene-coty commented
Normally there is no need of a space following colon in a French translation (if there is no text after it) ; it is only required to have an unbreakable space before a colon.

2022-10-13 19:39 UTC, merged

2022-10-13 19:39 UTC, elelay commented
Merged, thanks