delete tags before modifying
gpodder/gpodder pull request #1441
Opened 2022-11-28 07:31 UTC by Skitals

When "modify_tags" is enabled some episodes are getting carryover unrelated metadata prepended to the comments tag.

<img width="660" alt="Screenshot 2022-11-28 at 12 14 01 AM" src="https://user-images.githubusercontent.com/11912474/204217823-67db307f-b018-4a20-ba25-154c498eff7a.png">

This displays different in different players. In iTunes the bug isn't visible and it displays "People trying to coax each other [...]". However in other clients, such as Emby, it displays "preroll_1;postroll_1" and the show notes are not displayed at all.

This patch clears existing tags from the mp3 before writing the new ones, which fixes this bug.

2022-11-28 08:41 UTC, auouymous commented
What is the URL for this feed?

I don't use the tagging extension, but wouldn't removing tags delete those not set by gpodder, and also those which are empty in gpodder?

2022-11-28 09:13 UTC, Skitals commented
> What is the URL for this feed?
> 
> I don't use the tagging extension, but wouldn't removing tags delete those not set by gpodder, and also those which are empty in gpodder?

The feed in the example is The Daily from The New York Times: https://feeds.simplecast.com/54nAGcIl

It also happens in some episodes of This American Life: https://www.thisamericanlife.org/podcast/rss.xml

Yes, with this change when "modify_tags" is enabled all tags are stripped except ones set by gpodder.

2022-11-28 11:39 UTC, auouymous commented
Mutagen 1.45.1 and 1.46.0 delete all existing tags and don't set gpodder tags with or without this patch, even though the modify_tags code path is executed and the tags are all set to non-empty strings.

2022-11-28 15:11 UTC, Skitals commented
> Mutagen 1.45.1 and 1.46.0 delete all existing tags and don't set gpodder tags with or without this patch, even though the modify_tags code path is executed and the tags are all set to non-empty strings.

I am on mutagen 1.41.1 and that is not the case on gpodder 3.10.21 or 3.11.0. It works as expected with the exception of the excess metadata bug I am trying to fix. These are my extension settings:

```
  "extensions": {
    "enabled": [
      "update_feeds_on_startup",
      "rename_download",
      "tagging"
    ],
    "rename_download": {
      "add_podcast_title": false,
      "add_sortdate": true
    },
    "tagging": {
      "always_remove_tags": false,
      "auto_embed_coverart": true,
      "genre_tag": "Podcast",
      "modify_tags": true,
      "set_artist_to_album": true,
      "set_version": 4,
      "strip_album_from_title": true
    }
  },
```

2022-11-28 21:01 UTC, Skitals commented
new commit makes this an option that is defaulted off. If "remove_before_modify" is enabled existing tags are deleted before writing basic tags.

2022-11-29 06:23 UTC, auouymous requested changes

2022-11-30 01:27 UTC, auouymous approved these changes

2022-11-30 01:36 UTC, auouymous commented
LGTM, I'll squash and merge in a week if no one has a problem with the change.

Are you able to upgrade mutagen to 1.45.1 or newer? I'm curious to know if it is only broken for me on Gentoo, or if it is broken for everyone with a newer version, and no one uses the extension or realizes it is broken.

2022-11-30 01:38 UTC, auouymous commented
Ignore that, I thought you said 1.41.1 which wouldn't run for me on Python 3.10.

2022-11-30 12:49 UTC, Skitals commented
> Ignore that, I thought you said 1.41.1 which wouldn't run for me on Python 3.10.

FWIW I'm running xthursdayx/gpodder-docker. You can see what is installed [in the dockerfile](https://github.com/xthursdayx/gpodder-docker/blob/main/light/Dockerfile). I reinstalled the build-deps and did a git pull on gpodder to update to latest. Tagging works great with this one exception, which could have gone unnoticed for a long time since some players don't display the extra comment data.

2022-12-07 22:41 UTC, merged

2022-12-07 22:41 UTC, auouymous commented
Thank you for the improvement.