Fix an empty `mygpo.device.uid` to avoid mygpod failures.
gpodder/gpodder pull request #1668
Opened 2024-10-10 19:26 UTC by auouymous

Some platforms could return an empty hostname string. This resulted in mygpo always failing because it depends on the uid to be non-empty.

If hostname is empty, it now returns 'unknown'. It also appends a 32 digit identifier to the end of it to increase uniqueness of the uid.

Old installs are fixed by detecting an empty uid and generated a new value.

Fixes #751.
Fixes #1663.

@elelay Hostnames can be 64 to 255 characters in length, and this now appends 33 additional characters to that. It looks like uid on the server is limited to 50 characters, which doesn't even hold a valid hostname. Should I reduce the random identifier length?

2024-10-12 19:55 UTC, elelay commented
I don't know but it seems uid is indeed [max 64 chars](https://github.com/gpodder/mygpo/blob/master/mygpo/users/models.py#L235)
Please why append a uuid when hostname is known? Is it to support multiple installs per host?

2024-10-12 20:15 UTC, auouymous commented
The comment mentioned implementing a unique per-user ID. There is nothing stopping a user from having the same hostname on multiple computers, so the ID is technically always required for a unique uid.

After more thought, a 32bit ID "should" provide enough randomness to never produce the same value for a user with multiple machines, all with the same hostname. That would reduce it to 9 additional characters, reducing the chance of the uid overflowing the server's 50 char limit.

2024-10-13 19:26 UTC, elelay commented
sounds good!
where does the 50 char limit come from? It's [64 chars](https://github.com/gpodder/mygpo/blob/master/mygpo/users/models.py#L235), right?

2024-10-14 21:18 UTC, auouymous commented
I assume https://github.com/gpodder/mygpo/blob/80c41dc0c9a58dc0e85f6ef56662cdfd0d6e3b16/mygpo/web/forms.py#L105 is the same uid.

2024-10-26 09:01 UTC, auouymous commented
I also changed `-%08X` to `-%X` which will reduce the size below 9 extra digits on ~50% of installs.

2025-03-01 18:00 UTC, elelay requested changes
LGTM, with the truncation to avoid issues with mygpo

2025-03-01 18:00 UTC, elelay commented on src/gpodder/my.py
> +            self._config.mygpo.device.uid = util.get_hostname_uid()
```suggestion
            # conform to mygpo device uid limit
            # (https://github.com/gpodder/mygpo/blob/master/mygpo/users/models.py#L235)
            self._config.mygpo.device.uid = util.get_hostname_uid()[:64]
```

2025-03-02 04:42 UTC, auouymous commented on src/gpodder/my.py
> +            self._config.mygpo.device.uid = util.get_hostname_uid()
Should we instead trim the hostname inside `get_hostname_uid()` to `63-len(uid)`? That way we don't trim off the random uid and get long hostname that might be the same across all of a user's devices.

2025-03-02 10:00 UTC, elelay commented on src/gpodder/my.py
> +            self._config.mygpo.device.uid = util.get_hostname_uid()
yes

2025-03-02 10:03 UTC, elelay commented on src/gpodder/util.py
> +    hostname = get_hostname()
```suggestion
    # conform to mygpo device uid limit
    # (https://github.com/gpodder/mygpo/blob/master/mygpo/users/models.py#L235)
    hostname = get_hostname()[:64 - len(uid) - 1]
```

2025-03-02 10:06 UTC, elelay approved these changes

2025-03-02 10:06 UTC, merged

2025-03-03 00:21 UTC, auouymous commented
I just noticed that https://github.com/gpodder/mygpo/blob/80c41dc0c9a58dc0e85f6ef56662cdfd0d6e3b16/mygpo/web/forms.py#L105 in my comment above was never resolved, is it being limited to 50 there?

2025-03-03 19:04 UTC, elelay commented
yes, the web forms is more restrictive than the db. I don't know why