Remove the redundant application uniqueness test
gpodder/gpodder pull request #1693
Opened 2024-12-26 09:36 UTC by tpikonen

Gtk.Application (which gPodder uses already) ensures uniqueness without extra code.

Add a signal handler to 'notify::is-registered' which checks if the current instance is remote (i.e. gPodder is already running) and logs the same message about Dbus activation as before.

2024-12-28 19:08 UTC, elelay commented
we lost `--subscribe` in the battle...

2024-12-28 21:48 UTC, tpikonen commented
Ah, thanks for noticing.

There's now a new app action which implements the `--subscribe` option. It notably does not use the hand-coded Dbus API, but activates the action through `activate_action()` which calls the Dbus method which is automatically defined on the 'org.gtk.Actions' interface on '/org/gpodder/gpodder' object on 'org.gpodder.gpodder' name on the bus (isn't Dbus great).

These shell commands give an idea on what's defined by GLib and GTK on the bus:

```shell
busctl --user introspect org.gpodder.gpodder /org/gpodder/gpodder
busctl --user call org.gpodder.gpodder /org/gpodder/gpodder org.gtk.Actions List
```

2025-01-18 17:47 UTC, auouymous requested changes

2025-01-18 17:47 UTC, auouymous commented on bin/gpodder
> -    Warning: python-dbus not found. Disabling D-Bus support.
This message is misleading because dbus is not optional and can't be disabled, which is why gpodder has fake dbus for Windows and Mac builds. I think it fails to import dbus after this point, and removing this warning message will make it harder to diagnose the problem.

2025-01-19 16:51 UTC, tpikonen commented on bin/gpodder
> -    Warning: python-dbus not found. Disabling D-Bus support.
Should I move the try ... except and the message to `app.py`, where the next `import dbus` happens?

As the plan here is to eventually remove the use of dbus-python and port the needed things to GDBus from GLib, I would like to remove the dbus import from all files which do not need it.

2025-01-19 16:56 UTC, tpikonen commented
Does this MR work on Windows or Mac without Dbus? There are explicit calls to `Gio.bus_get_sync()` and `Gio.DBusConnection.flush_sync()`, which perhaps need a working Dbus.

Could someone who uses gPodder on Windows (like @masoudd) test this?

2025-01-19 23:53 UTC, auouymous commented on bin/gpodder
> -    Warning: python-dbus not found. Disabling D-Bus support.
There is a non-zero chance a "new feature" that uses dbus could be inserted in the startup chain before dbus is replaced, but I don't see a case where `app.py` isn't always next.

2025-01-20 18:16 UTC, masoudd commented
> Does this MR work on Windows or Mac without Dbus? There are explicit calls to `Gio.bus_get_sync()` and `Gio.DBusConnection.flush_sync()`, which perhaps need a working Dbus.
> 
> Could someone who uses gPodder on Windows (like @masoudd) test this?

I tested the build artifacts from [appveyor](https://ci.appveyor.com/project/elelay/gpodder/builds/51236633/artifacts) for commit 0e4edd1 and tldr: it does not work

First I had the release 3.11.5 installed and open, tested the portable build and it starts as many instances as desired. Then I installed the installer artifact and it also can be opened more than once. Having the portable and installed build open you can open either of them again.
running `gpodder-cmd.exe -v` I see nothing of interest except for this line:

`(gpodder-cmd.exe:17276): GLib-GIO-WARNING **: 21:23:52.270: win32 session dbus binary not found`

Here is the output of the `gpodder-cmd.exe -v` while there is already another instance open:

<details><summary>Debug output</summary>
<code>

D: windows build; registry home = None
D: windows build; documents home = C:\Users\newuser2\Documents\gPodder
1737396553.655713 [gpodder.log] DEBUG: ==== gPodder starts up (ui=gtk) ===
1737396554.277966 [gpodder.registry] DEBUG: Registering download_url resolver: <function youtube_real_download_url at 0x04a04e88>
1737396554.282959 [gpodder.registry] DEBUG: Registering download_url resolver: <function vimeo_real_download_url at 0x04a18b18>
1737396554.568002 [gpodder.sync] INFO: iPod sync not available
1737396554.578004 [gpodder.sync] INFO: eyeD3 MP3 not available
1737396554.646910 [gpodder.gtkui.shownotes] INFO: No WebKit2 gobject bindings, so no HTML shownotes

(gpodder-cmd.exe:7384): GLib-GIO-WARNING **: 21:39:14.698: win32 session dbus binary not found
1737396554.718359 [gpodder.extensions] DEBUG: Found extension "audio_converter" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\audio_converter.py
1737396554.718359 [gpodder.extensions] DEBUG: Found extension "command_on_download" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\command_on_download.py
1737396554.718359 [gpodder.extensions] DEBUG: Found extension "concatenate_videos" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\concatenate_videos.py
1737396554.718359 [gpodder.extensions] DEBUG: Found extension "enqueue_in_mediaplayer" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\enqueue_in_mediaplayer.py
1737396554.787523 [enqueue_in_mediaplayer] WARNING: Win32 player not found: HKEY_CLASSES_ROOT\Winamp.File\shell\Enqueue\command ([WinError 2] The system cannot find the file specified)
1737396554.787523 [enqueue_in_mediaplayer] WARNING: Win32 player not found: HKEY_CLASSES_ROOT\foobar2000.MP3\shell\enqueue\command ([WinError 2] The system cannot find the file specified)
1737396554.787523 [gpodder.extensions] INFO: Module loaded: E:\Program Files (x86)\gPodder\share\gpodder\extensions\enqueue_in_mediaplayer.py
1737396554.787523 [gpodder.extensions] DEBUG: Found extension "episode_website_context_menu" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\episode_website_context_menu.py
1737396554.787523 [gpodder.extensions] DEBUG: Found extension "filter" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\filter.py
1737396554.792525 [gpodder.extensions] DEBUG: Found extension "gtk_statusicon" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\gtk_statusicon.py
1737396554.792525 [gpodder.extensions] DEBUG: Found extension "minimize_on_start" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\minimize_on_start.py
1737396554.792525 [gpodder.extensions] DEBUG: Found extension "mpris-listener" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\mpris-listener.py
1737396554.792525 [gpodder.extensions] DEBUG: Found extension "normalize_audio" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\normalize_audio.py
1737396554.792525 [gpodder.extensions] DEBUG: Found extension "notification" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\notification.py
1737396554.797526 [notification] INFO: Could not find PyNotify.
1737396554.797526 [gpodder.extensions] INFO: Module loaded: E:\Program Files (x86)\gPodder\share\gpodder\extensions\notification.py
1737396554.797526 [gpodder.extensions] DEBUG: Found extension "notification-win32" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\notification-win32.py
1737396554.797526 [gpodder.extensions] INFO: Module loaded: E:\Program Files (x86)\gPodder\share\gpodder\extensions\notification-win32.py
1737396554.802526 [gpodder.extensions] DEBUG: Found extension "podverse" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\podverse.py
1737396554.802526 [gpodder.extensions] DEBUG: Found extension "rename_download" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\rename_download.py
1737396554.804623 [gpodder.extensions] DEBUG: Found extension "rm_ogg_cover" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\rm_ogg_cover.py
1737396554.809586 [gpodder.extensions] DEBUG: Found extension "rockbox_convert2mp4" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\rockbox_convert2mp4.py
1737396554.809586 [gpodder.extensions] DEBUG: Found extension "rockbox_coverart" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\rockbox_coverart.py
1737396554.809586 [gpodder.extensions] DEBUG: Found extension "sonos" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\sonos.py
1737396554.809586 [gpodder.extensions] DEBUG: Found extension "subscription_stats" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\subscription_stats.py
1737396554.809586 [gpodder.extensions] DEBUG: Found extension "tagging" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\tagging.py
1737396554.809586 [gpodder.extensions] DEBUG: Found extension "taskbar_progress" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\taskbar_progress.py
1737396554.824589 [comtypes] DEBUG: CoInitializeEx(None, 2)
1737396554.879669 [comtypes.client._code_cache] INFO: Imported existing <module 'comtypes.gen' from 'E:\\Program Files (x86)\\gPodder\\lib\\python3.12\\site-packages\\comtypes\\gen\\__init__.py'>
1737396554.879669 [comtypes.client._code_cache] INFO: Using writeable comtypes cache directory: 'E:\Program Files (x86)\gPodder\lib\python3.12\site-packages\comtypes\gen'
1737396554.884670 [gpodder.extensions] INFO: Module loaded: E:\Program Files (x86)\gPodder\share\gpodder\extensions\taskbar_progress.py
1737396554.884670 [comtypes.client] DEBUG: {56FDF344-FD6D-11d0-958A-006097C9A090} -> {56FDF344-FD6D-11D0-958A-006097C9A090}
1737396554.887693 [comtypes.client] DEBUG: CoCreateInstance({56FDF344-FD6D-11D0-958A-006097C9A090}, clsctx=None, interface=<class 'taskbar_progress.ITaskbarList3'>)
1737396554.889716 [gpodder.extensions] DEBUG: Found extension "ted_subtitles" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\ted_subtitles.py
1737396554.894702 [gpodder.extensions] DEBUG: Found extension "ubuntu_appindicator" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\ubuntu_appindicator.py
1737396554.894702 [gpodder.extensions] DEBUG: Found extension "ubuntu_unity" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\ubuntu_unity.py
1737396554.894702 [gpodder.extensions] DEBUG: Found extension "update_feeds_on_startup" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\update_feeds_on_startup.py
1737396554.894702 [gpodder.extensions] DEBUG: Found extension "video_converter" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\video_converter.py
1737396554.894702 [gpodder.extensions] DEBUG: Found extension "youtube-dl" in E:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py
1737396555.031951 [gpodder.extensions] INFO: Module loaded: E:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py
1737396555.031951 [youtube-dl] INFO: Registering youtube-dl. (using yt-dlp 2024.12.23)
1737396555.031951 [gpodder.reg [...]

2025-01-20 18:22 UTC, masoudd commented
I think I need to add that the release 3.11.5 also behaves like this. The uniqueness is not working on windows currently

2025-01-20 23:32 UTC, auouymous commented
The Windows and Mac builds do not have dbus support, because it wasn't available until a couple years ago, see #1253. I don't know if it is available on Mac yet.

A fake dbus module is provided by gpodder to turn dbus calls into no-ops. Those builds have never prevented multiple instances and can't use the MPRIS extension.

2025-01-21 08:43 UTC, tpikonen commented
> I tested the build artifacts from [appveyor](https://ci.appveyor.com/project/elelay/gpodder/builds/51236633/artifacts) for commit [0e4edd1](https://github.com/gpodder/gpodder/commit/0e4edd19049984d9309d4d6cf5d75cd9e72fad79) and tldr: it does not work

Thanks for testing. I did not expect the uniqueness to work without Dbus, but suspected that the explicit calls to Dbus functions might cause unhandled exceptions or worse.

It looks like dbus-python could be replaced with GDBus without fake modules on Windows.

2025-01-21 10:35 UTC, auouymous commented
Might need to rebase to remove 3.7 testing.

2025-02-28 17:12 UTC, elelay commented
Re migrating to GDBus, see https://stackoverflow.com/a/54120702
I've not tried it but there is an example linked from the stackoverflow: https://wiki.gnome.org/HowDoI/GDBusPython

2025-03-01 11:43 UTC, tpikonen commented
It generally looks like the python dbus interfaces have a limited lifetime: The last commit on pydbus was 7 years ago and on dasbus 2 years ago. dbus-next is 3 years stale, but its fork dbus-fast seems to be active.

GDBus comes free with GLib, which we have to use anyway, and I think we can live with the slightly clunky API.

2025-03-01 16:14 UTC, elelay commented
LGTM. It works on Linux.
@auouymous merge at will :-)

Regarding moving away from dbus-python I'm also in favor of GDBus but I haven't used it before. My note was to save what I found in case somebody was interested.

2025-03-02 03:57 UTC, merged

2025-03-02 03:58 UTC, auouymous commented
Thank you for doing this.