Do not show new episodes on view->Downloaded
gpodder/gpodder pull request #897
Opened 2020-11-09 09:59 UTC by tpikonen

I'm seeing new, but not downloaded episodes in the episode list when I select 'View->Downloaded episodes' from the menu. This change fixes this view to only show episodes which are downloaded.

2020-11-09 12:08 UTC, elelay commented
Thanks for the patch. See https://github.com/gpodder/gpodder/issues/468#issuecomment-510179540 for proposal to add a checkbox "always show new episodes" in combination with this.

2020-11-09 13:35 UTC, tpikonen commented
Ok, I implemented the checkbox. It works for me but please test.

2020-11-09 14:35 UTC, elelay requested changes
I haven't tested it yet but it looks fine!
Just change the one remark.

I want to push a new release this week and already polled translators for updates so I won't merge your PR just now.
It will be merged next week, though.

Thanks,

2020-11-09 14:35 UTC, elelay commented on src/gpodder/gtkui/model.py
> +                    view_show_downloaded = True
Replace by `view_show_downloaded = self._config.ui.gtk.episode_list.always_show_new`

2020-11-09 15:48 UTC, tpikonen commented on src/gpodder/gtkui/model.py
> +                    view_show_downloaded = True
Good catch, I've pushed a fixed version.

2020-11-10 09:15 UTC, elelay commented on src/gpodder/config.py
> +                'always_show_new': False,
can you make it True by default?

2020-11-10 09:16 UTC, elelay approved these changes
perfect, thanks.
Just make it checked by default for backward compatibility.

2020-11-10 20:56 UTC, tpikonen commented on src/gpodder/config.py
> +                'always_show_new': False,
Done, and pushed.

2020-11-11 11:51 UTC, elelay commented
Great, thanks!
Will be merge as is

2020-11-24 16:27 UTC, merged

2020-11-24 16:28 UTC, elelay commented
Merged, thanks